version: '1'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'scrape'
      MYSQL_USER: 'prshete'
      MYSQL_PASSWORD: 'prshete@1234'
      MYSQL_ROOT_PASSWORD: 'prshete@1234'
    volumes:
      - ./data:/var/lib/mysql
  web:
    build: ./scrapper
    ports:
      - "8000:8000"
    depends_on:
      - db
